apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:  
    project: roboshop
    env: dev-env
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9


# kubectl apply -f 03-multicontainer.yaml