apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: COURSE
      value: "KUBERENETS"
    - name: TRAINER
      value: "SIVAKUMAR REDDY M"




# kubect apply -f 07-env.yaml

# kubectl exec -it envar-demo -- bash

# env

# After executing the line no 22(kubectl exec -it envar-demo -- bash) and 24(env) commands, we can see the environment variables inside the pod

# exit --- to come out of the pod

