apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: COURSE
      value: "KUBERENETS"
    - name: TRAINER
      value: "SIVAKUMAR REDDY M"




# kubect apply -f 07-env.yaml

# kubectl exec -it envar-demo -- bash

# env

# After executing the line no 22(kubectl exec -it envar-demo -- bash) and 24(env) commands, we can see the environment variables inside the pod

# exit --- to come out of the pod

# code and configuration. try to keep configuration always outside(loose coupling)

# we try to keep the configuration outside of pod definition. i.e configmap

# And finally, we keep env variables and the configs in a configmap and we refer them inside the pod.


