apiVersion: v1
kind: Pod
metadata:
  name: env-secret
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: pod-secret

# Commands

# kubectl apply -f 11-pod-secret.yaml

# kubectl get pods

# kubectl exec -it env-secret -- bash 

# env

# now we can see the username and password which we mentioned in 10-secret.yaml

# And this is not say way to mention the secrets here. Please refer, base64-decoding.png to know how we can decode the password

# So, we have to encrypt the screts, not encoding

# encrypting means publickkey and privatekeys i.e., who ever has both the keys only can view the password. where as encoding means, who ever knows the encoded value, they can decrypt and view the password and can miss use it.

