
# A Classic loadbalancer will be created and all our nodes will be attached as a target groups and a specific port will be opened on all the instances
# And LB will change the ingress rules of the SG of the loadbalancer stating to allow all the traffic coming from the loadbalancer      

apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    purpose: service-lb-demo
spec:
  type: LoadBalancer
  selector:
    purpose: service-lb-demo
    project: roboshop
    environment: dev
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    purpose: service-lb-demo
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx